---
title: "ass2_mia"
output: html_document
date: "2023-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# packages
pacman::p_load(tidyverse,
        here,
        posterior,
        cmdstanr,
        brms, tidybayes)

```


## Matching pennies with LSWS 


### Simulating data
```{r}
# set up
ntrials <- 120
nagents <- 10
bias <- 0.6
follow_bias <- 0.8
rate <- 0.5
noise <- 0.2
beta <- 0.65
confidencerate <- 0.05 
```


```{r}
RandomAgentNoise_f <- function(rate, noise) {
  choice <- rbinom(1, 1, rate)
  if (rbinom(1, 1, noise) == 1) 
  {choice = rbinom(1, 1, 0.5)}
  return(choice)
  }
```

```{r}
randomChoice <- array(NA, ntrials)

for (t in seq(ntrials)) { 
      randomChoice[t] <- RandomAgentNoise_f(rate, noise)
    }
d1 <- tibble(trial = seq(ntrials), Other = randomChoice, rate, noise)

```


```{r}

# Now we create the memory agent whose beta changes based on winning or losing
MemoryAgent_f <- function(bias, beta, memory, confidence){
    choice = rbinom(1, 1, inv_logit_scaled(bias + (beta + confidence) * memory))
  return(choice)
}


```

```{r}
# memory agent simulation function
df <- NULL
sim_mem <- function(nagents, ntrials, rate, noise, bias, beta, confidencerate){

  for (agent in 1:nagents){
    self <- rep(NA, ntrials) 
    other <- rep(NA, ntrials) 
    memory <- array(NA, ntrials)
    confidence <- rep(NA, ntrials)
    
    self[1] <- rbinom(1, 1, 0.5)
    other[1] <- rbinom(1, 1, 0.5)
    confidence[1] <- 0
    
    # making other's choices
    for (t in 1:ntrials) { 
          other[t] <- RandomAgentNoise_f(rate, noise)
        }
    
    # making memory
    for (t in 1:ntrials){
      if (t == 1) {
        memory[t] = 0.5
      } 
      if (t < ntrials){
          memory[t + 1] = memory[t] + ((other[t] - memory[t]) / t)
          if (memory[t + 1] == 0){memory[t + 1] = 0.01}
          if (memory[t + 1] == 1){memory[t + 1] = 0.99}
      }
    }
    
    # making self
    for (t in 2:ntrials){ # first we update confidence based on previous trial
      if (other[t-1] == self[t-1]){
        confidence[t] = confidence[t-1] + confidencerate
      }
      else {
        confidence[t] = confidence[t-1] - confidencerate
      }
      
      self[t] <- MemoryAgent_f(bias, beta, memory[t], confidence[t])
    }
    
    temp <- tibble(agent, trial = seq(ntrials), bias, beta, self, other, memory, 
                   confidence = round(confidence, 2))

    if (exists("df")) { df <- rbind(df, temp)} else{df <- temp} 
    
  }
  return (df)
}

d1 <- sim_mem(nagents, ntrials, rate, noise, bias, beta, confidencerate)

d1 <- d1 %>% 
  mutate(beta_conf_combined = beta + confidence)
```


```{r}
# LSWS agent function
LSWSAgentBias_f <- function(prevChoice, Feedback, bias, follow_bias){ 
  # if the agent won on previous round - shift 
  if (Feedback == 1 & prevChoice == 0){
    choice = rbinom(1, 1, inv_logit_scaled(bias + follow_bias * 1))
  }
  else if (Feedback == 1 & prevChoice == 1){
    choice = rbinom(1, 1, inv_logit_scaled(bias + follow_bias * -1))
  }
  # if the agent lost - stay
  else if (Feedback == 0 & prevChoice == 0){
    choice = rbinom(1, 1, inv_logit_scaled(bias + follow_bias * -1))
  }
  else if (Feedback == 0 & prevChoice == 1){
    choice = rbinom(1, 1, inv_logit_scaled(bias + follow_bias * 1))
  }
  return(choice) 
}
```


```{r}
df <- NULL
sim <- function(nagents, ntrials, bias, follow_bias, rate, noise){

  for (agent in 1:nagents){
    self <- rep(NA, ntrials) 
    other <- rep(NA, ntrials) 
    feedback <- rep(NA, ntrials)
    self[1] <- rbinom(1, 1, 0.5)
    other[1] <- rbinom(1, 1, 0.5)
    # HERE Riccardo REMOVED THE FEEDBACK LINE
    
    for (i in 2:ntrials){ # HERE Riccardo GENERATES FEEDBACK BASED ON THE PREVIOUS TRIAL TO INFORM THE CURRENT TRIAL
      if (self[i-1] == other[i-1]){ 
          feedback[i-1] = 1 } 
        else {
          feedback[i-1] = 0 } 
        self[i] <- LSWSAgentBias_f(self[i-1], feedback[i-1], bias, follow_bias) # HERE Riccardo USEs PREVIOUS CHOICE AND PREV FEEDBACK TO GENERATE CURRENT CHOICE
        other[i] <- RandomAgentNoise_f(rate = 0.5, noise = 0.1) 
    }   
    feedback[ntrials] <- ifelse(self[ntrials] == other[ntrials], 1, 0) # HERE Riccardo GENERATES FEEDBACK FOR THE LAST TRIAL, TO AVOID LOSING THAT ROW LATER
    temp <- tibble(agent_nr = agent, bias, follow_bias, self, other, feedback, trial = seq(ntrials)) # HERE Riccardo SAVES ALSO OTHER; TO BETTER UNDERSTAND WHAT THE AGENT IS DOING

    if (exists("df")) { df <- rbind(df, temp)} else{df <- temp} 
    
  }
  return (df)
}
sim_df <- sim(nagents, ntrials, bias, follow_bias, rate, noise)

# HERE Riccardo LAGS THE OUTCOME_HAND: I WANT THE VARIABLE INFORMED BY PREVIOUS CHOICE AND FEEDBACK TO APPEAR IN THE CURRENT TRIAL
sim_df$outcome_hand <- ifelse(lag(sim_df$feedback == 1 & sim_df$self == 0,1) | 
                              lag(sim_df$feedback == 0 & sim_df$self == 1,1) , 
                              1, -1)

# Riccardo's PROCEDURE GENERATED SOME NAs (no outcome hand for the first trial in each agent), HE REMOVES THOSE ROWS 
sim_df <- sim_df[complete.cases(sim_df),]

```

### let's do some stan

```{r}
sim_df <- sim_df %>% 
  filter(agent_nr == 1)

data <- list(n = 119, c = sim_df$self, outcome_hand = sim_df$outcome_hand)

file <- file.path("LSWS.stan")
mod <- cmdstan_model(file, 
                     cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))

# The following command calls Stan with specific options.
samples <- mod$sample(
  data = data,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  refresh = 0,
  max_treedepth = 20,
  adapt_delta = 0.99,
)
```
```{r}
draws_df <- as_draws_df(samples$draws())

```

```{r}
# Checking the model's chains
ggplot(draws_df, aes(.iteration, follow_bias, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()

# Plotting the estimates against the prior distribution
# the dashed line is the true rate

# add a prior for theta (ugly, but we'll do better soon)
draws_df <- draws_df %>% 
  mutate(fb_prior = rnorm(nrow(draws_df), 0, 1)
)

# Now let's plot the density for theta (prior and posterior)

ggplot(draws_df) +
  geom_density(aes(follow_bias), fill = "blue", alpha = 0.3) +
  geom_density(aes(fb_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = 0.8, linetype = "dashed", color = "black", linewidth = 1.5) +
  xlab("Follow Bias") +
  ylab("Posterior Density") +
  theme_classic()

```

```{r}
# add a prior for theta (ugly, but we'll do better soon)
draws_df <- draws_df %>% 
  mutate(b_prior = rnorm(nrow(draws_df), 0, 1)
)

# Now let's plot the density for theta (prior and posterior)

ggplot(draws_df) +
  geom_density(aes(bias), fill = "blue", alpha = 0.3) +
  geom_density(aes(b_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = 0.6, linetype = "dashed", color = "black", linewidth = 1.5) +
  xlab("Bias") +
  ylab("Posterior Density") +
  theme_classic()
```
# Memory agent
```{r}
data <- list(n = 120, h = d1$Self, other = d1$Other)
file <- file.path("memoryagent.stan")
mod <- cmdstan_model(file, 
                     cpp_options = list(stan_threads = TRUE),
                     stanc_options = list("O1"))

# The following command calls Stan with specific options.
samples <- mod$sample(
  data = data,
  seed = 123,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  refresh = 0,
  max_treedepth = 20,
  adapt_delta = 0.99,
)

```
```{r}
draws_df <- as_draws_df(samples$draws())


ggplot(draws_df, aes(.iteration, bias, group = .chain, color = .chain)) +
  geom_line() +
  theme_classic()

draws_df <- draws_df %>% 
  mutate(b_prior = rnorm(nrow(draws_df), 0, .7),
         beta_prior = rnorm(nrow(draws_df), 0, 1)
)

# Now let's plot the density for theta (prior and posterior)

ggplot(draws_df) +
  geom_density(aes(bias), fill = "blue", alpha = 0.3) +
  geom_density(aes(b_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = 0.8, linetype = "dashed", color = "black", linewidth = 1.5) +
  xlab("Bias") +
  ylab("Posterior Density") +
  theme_classic()

ggplot(draws_df) +
  geom_density(aes(beta), fill = "blue", alpha = 0.3) +
  geom_density(aes(beta_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = 0.8, linetype = "dashed", color = "black", linewidth = 1.5) +
  xlab("Beta") +
  ylab("Posterior Density") +
  theme_classic()
```
